(define-key esc-map "\C-h" 'help-for-help)
(global-set-key "\C-h" 'backward-delete-char-untabify)
(global-set-key "\C-xm" 'vm-mail)
(local-set-key (kbd "M-!") 'isearch-forward)
(local-set-key (kbd "M-~") 'isearch-forward)
(global-set-key (kbd "C-M-@") 'C-m-at)
(global-set-key (kbd "C-M-a") 'C-M-a)
(global-set-key (kbd "C-M-b") 'C-M-b)
(local-set-key (kbd "C-M-_") 'C-M-_)
(local-set-key (kbd "<C-M-down>") 'C-M-down)
(local-set-key (kbd "M-\\") 'M-backspace)
(local-set-key (kbd "M-^") 'M-caret)
(local-set-key (kbd "ESC <right>") 'ESC-right)
(local-set-key (kbd "M-s ESC") 'M-s-ESC)
(local-set-key (kbd "M-`") 'M-backtick)
